openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /helloworld:
    get:
      summary: Returns Simple Message.
      description: N/A.
      responses:
        '200':    # status code
          description: Hello World! - Some random number
          content:
            application/json:
              schema: 
                type: string
